### ISSUE TITLE
Class not being removed when navigating to new page...

### ISSUE THREAD

**Issue by dallasbpeters** [michaek/middleman-navigation#10]
For some reason a middleman upgrade recently caused the classes on the `<li>` items to stick around even after navigation to a new page. Any ideas?
## Setup

Gemfile

```
gem "middleman-navigation"
```

Gemfile.lock

```
middleman-navigation (1.0.4)
  middleman-core (~> 3.2.1)
  simple-navigation (> 3.0.0)
```

config.rb

```
activate :navigation
```
## Screeshots

![screenshot 2014-03-20 12 29 43](https://f.cloud.github.com/assets/91672/2475279/5884f448-b055-11e3-8f9e-c15f0b4f98c1.png)

![screenshot 2014-03-20 12 29 30](https://f.cloud.github.com/assets/91672/2475277/56ce7340-b055-11e3-971f-ff5945f1a8ee.png)

**Comment by michaek** [comment]
This one sounds familiar to me - I'll take a look at it.

**Comment by dallasbpeters** [comment]
@michaek any luck here?
