### ISSUE TITLE
Submenus are not rendered

### ISSUE THREAD

**Issue by michaek** [michaek/middleman-navigation#2]
Child menus do not seem to render at all.

**Comment by cseelus** [comment]
I thought this behavior has to be explicitly enabled somewhere (config?), like with [simple-navigation](https://github.com/andi/simple-navigation/wiki/Renderer::List), where `:expand_all` is set to `false` by default and has to be set to `true` first.

**Comment by michaek** [comment]
I believe that I've tested this with :expand_all => true, but I'd need to go back and take another look. When I get a chance, I'll set up testing so we can reproduce it.
