### ISSUE TITLE
Index page is always assigned css classes for active/selected state

### ISSUE THREAD

**Issue by cseelus** [michaek/middleman-navigation#3]
Unfortunately another bug: The index page element inside the navigation is always assigned the following css-classes, even if another page is currently opened: 

```
selected 
simple-navigation-active-leaf
```

**Comment by michaek** [comment]
I suspect this has to do with the :highlights_on matcher that we're using to set active state: https://github.com/michaek/middleman-navigation/blob/master/lib/middleman-navigation/tree.rb#L43

Are you using :directory_indexes in your middleman site? Which version of the middleman-navigation gem are you working from? (From Github?)

Thanks for reporting this! When I get a few minutes, I'll set up tests and get coverage for it.

**Comment by cseelus** [comment]
Yeah, seems so.

I'm using :directory_indexes, but only in the build configuration of course, where it should cause no problems while developing. Disabled it though now for my testing project, just to avoid any unforeseen issues.
And I'm working from the middleman-navigation gem directly from github for this testing project.

Thanks for caring!

**Comment by wynn76** [comment]
Same Issue, Using middleman-navigation 1.0.2.

**Comment by michaek** [comment]
Yep, this is a real issue, I just haven't had any time to devote to testing and resolving it. I do believe that the line that I linked to above is the source of the issue, if anyone else would like to take a crack at it.
