### ISSUE TITLE
NoMethodError at /

### ISSUE THREAD

**Issue by CaliMer0** [michaek/middleman-navigation#5]
First of all, I am quite new to middleman so I hope the error is not on my side.

I get the following error as soon as I use the =render_navigation.
NoMethodError at /
undefined method `html_safe' for #String:0x00000102984ab0
Ruby    /Users/.../.rvm/gems/ruby-1.9.3-p194@tools-middleman-html5/gems/simple-navigation-3.10.1/lib/simple_navigation/adapters/padrino.rb: in content_tag, line 15
Web     GET localhost/

**Comment by michaek** [comment]
Hm. html_safe is a string addition that might not be available in padrino/middleman. It could be that a newer version of Simple Navigation is trying to use it, but I haven't tried to track this down yet..

**Comment by CaliMer0** [comment]
Thanks a lot for the fast reply.
Which version of "Simple Navigation" are you using?
Any chance a downgrade might help?
Thanks a lot again

**Comment by michaek** [comment]
I was using 3.10.0 the last time it was working for me. It does look like this commit may have introduced the issue: https://github.com/andi/simple-navigation/commit/6acabf878b2b54c3f2572c7b05a05ee10ab57a9d

**Comment by CaliMer0** [comment]
Is there a workaround somehow?
Just require =3.10.0 or some definition of html_safe as to only return the content?

Best wishes

**Comment by michaek** [comment]
Yes, just use 3.10.0 for now. The html_safe method comes from Rails' ActiveSupport: http://guides.rubyonrails.org/active_support_core_extensions.html (You could include ActiveSupport, too, I imagine.) If I were designing this again, I would not build on top of simple_navigation - it has too many rough edges.

**Comment by CaliMer0** [comment]
Thank's again.
A simple "require 'active_support/core_ext/string/output_safety'" in config.rb fixes the problem just fine.

Thank's again.
