### ISSUE TITLE
NoMethod Error

### ISSUE THREAD

**Issue by dallasbpeters** [michaek/middleman-navigation#7]
Now I'm getting this...

```
NoMethodError: undefined method `html_safe' for "<a class=\"selected\" href=\"/\">Custom Title</a>":String
```

Any thoughts?

**Comment by michaek** [comment]
I believe that simple-navigation tries to html_safe the content, but if that method doesn't exist on the string, you'll have problems. https://github.com/andi/simple-navigation/blob/5cf5c7af34227c9a8dfc7015d7ba4e0bd58520b7/lib/simple_navigation/adapters/padrino.rb#L15
