### ISSUE TITLE
FrontMatter is no longer a module

### ISSUE THREAD

**Issue by jiho** [michaek/middleman-navigation#8]
Hi. I get this:

```
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/middleman-navigation-1.0.2/lib/
middleman-navigation/front_matter.rb:5:in `<module:CoreExtensions>': FrontMatter is not a
module (TypeError) from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/middleman-navigation-1.0.2/lib/
middleman-navigation/front_matter.rb:4:in `<top (required)>' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/middleman-navigation-1.0.2/lib/
middleman-navigation.rb:3:in `require' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/middleman-navigation-1.0.2/lib/
middleman-navigation.rb:3:in `<top (required)>' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runti
me.rb:72:in `require' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runti
me.rb:72:in `block (2 levels) in require' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runti
me.rb:70:in `each' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runti
me.rb:70:in `block in require' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runti
me.rb:59:in `each' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runti
me.rb:59:in `require' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:13
2:in `require' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/middleman-core-3.1.5/lib/middle
man-core/load_paths.rb:38:in `setup_load_paths' from
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/middleman-core-3.1.5/bin/middle
man:10:in `<top (required)>' from /usr/local/Cellar/ruby/2.0.0-p247/bin/middleman:23:in
`load' from /usr/local/Cellar/ruby/2.0.0-p247/bin/middleman:23:in `<main>'
```

when I try to load the extension with Middleman 3.1.5.

Looking through the code of MiddleMan, FrontMatter indeed seems to be a class rather than a module now.

I would very much welcome a fix since your extension seems the most practical one to generate a full navigation automatically. Thanks in advance.

**Comment by michaek** [comment]
It's possible I could fix this over the weekend, but if not I'd suggest either using an earlier version of Middleman or making the change yourself and throwing me a pull request.

**Comment by jiho** [comment]
If I could I would have done it gladly but unfortunately I am ruby noob :(

I'll wait over the week end and try to downgrade Middleman otherwise.

Thanks in advance for your efforts.

**Comment by michaek** [comment]
I took a look at this, and it'll require a non-trivial amount of work to get this working with Middleman 3.1.x. Unfortunately, I haven't been using Middleman recently, so I won't be able to dedicate time to resolving this. For now, I'd suggest using Middleman 3.0.x.

**Comment by bryanbraun** [comment]
Just wanted to chime in and confirm that I found the same issue on Middleman 3.1.5, but rolling back to 3.0.14 made the error go away.

**Comment by yannlossouarn** [comment]
Hi!

Any chance to get middleman-navigation's bug related to FrontMatter corrected? Please please please say yes! :)

**Comment by vladp** [comment]
I ran into the same issue. Also ruby novice, not sure what to do. I guess would appreciate recommending alternatives

**Comment by michaek** [comment]
I'll reiterate that this issue can be resolved easily by installing an earlier version of Middleman, < 3.1.0

**Comment by michaek** [comment]
I have updated the Readme to reflect the compatibility issue, referencing the last compatible version of Middleman, but I don't know if I'll have any availability to resolve this. A pull request would be welcome.

**Comment by yannlossouarn** [comment]
Any tips about where to start looking at for correcting the bug? I could try to have a look, even if I am a newbie at Ruby...

**Comment by andyl** [comment]
Just ran into this bug.  What is a good alternative to 'middleman-navigation' that works with Middleman 3.3 ??

**Comment by LeonB** [comment]
I'm having the same issue with Middleman 3.3.5

**Comment by michaek** [comment]
I'll take a look. I haven't used Middleman in some time, so I'm not keeping up with their releases!
