### ISSUE TITLE
[q] documentation/example

### ISSUE THREAD

**Issue by vladp** [michaek/middleman-navigation#9]
Hello I am new to the whole middleman stack.

I have installed and working with this middleman template
https://github.com/nathos/amicus

I have successfully installed middleman-navigation

Now, what files in that template above would I need to modify to enable a multi-page static site with navigation ?

thx

**Comment by michaek** [comment]
Sorry, I won't be able to help out with general guidance. You can look at the text fixtures for an example. https://github.com/michaek/middleman-navigation/tree/master/fixtures/basic-app
